version: '3'

services:

  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=heartsm0nG0user
      - MONGO_INITDB_ROOT_PASSWORD=61#gHknf2!&0oz^52
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./database/mongo-db:/data/db
    networks:
      - nexthearts-network

  # nginx built inside
  nexthearts-app:
    image: docker-nexthearts
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - 4050:3000 
    environment:
      - MONGO_URI=mongo
      - MONGO_PORT=27017
      - MONGO_COLLECTION=nexthearts
      - MONGO_USER=heartsm0nG0user
      - MONGO_PASSWORD=61#gHknf2!&0oz^52

      # PROVIDERS
      - GITHUB_ID=
      - GITHUB_SECRET=
      - FACEBOOK_ID=
      - FACEBOOK_SECRET=

      - NEXTAUTH_URL=https://next-hearts.williamusic.com
    depends_on:
      - mongo
    networks:
      - nexthearts-network
      - nginx-prox-mgmt-3_default
      # add to ngnix-prox-mgmt network

networks:
  nexthearts-network:
    driver: bridge
  nginx-prox-mgmt-3_default: # so we can call service by DNS
    driver: bridge

volumes:
  mongo-db:
